export enum BankAccountErrorCodes {
  INVALID_AGENCY_NUMBER = "INVALID_AGENCY_NUMBER",
  INVALID_AGENCY_CHECK_NUMBER = "INVALID_AGENCY_CHECK_NUMBER",
  INVALID_ACCOUNT_NUMBER = "INVALID_ACCOUNT_NUMBER",
  INVALID_ACCOUNT_CHECK_NUMBER = "INVALID_ACCOUNT_CHECK_NUMBER",
  AGENCY_CHECK_NUMBER_DONT_MATCH = "AGENCY_CHECK_NUMBER_DONT_MATCH",
  ACCOUNT_CHECK_NUMBER_DONT_MATCH = "ACCOUNT_CHECK_NUMBER_DONT_MATCH",
  INVALID_BANK_NUMBER = "INVALID_BANK_NUMBER",
}
